### ISSUE TITLE
[Feature Request] Template Changed after 23.10.10

### ISSUE THREAD

**Issue by frinkleko** [ShevonKuan/SCUT-thesis#1]
**为何需要**
根据23.10.10 发布的[2024届本科毕业论文通知](https://jw.webvpn.scut.edu.cn/zhinan/cms/article/view.do?type=second&id=ff80808180646215018b174616430487)附件1可知，本科生毕业论文模板又发生了一些变化😂。其中明显可看出差别的包括

1. 新增了学位论文版权授权书
![image](https://github.com/ShevonKuan/SCUT-thesis/assets/32212221/9ac9fcfa-40ed-45b2-8a1c-7117aa938ea5)
2. 调整了“本科毕业设计（论文）”字样的布局
![image](https://github.com/ShevonKuan/SCUT-thesis/assets/32212221/7dab2fb3-db97-465a-838c-a6ae6bc056f5)
其余可能还存在没有注意到的差别，还待进一步检查。

**该需求为个人需求吗**
否

感谢你的精彩工作；未来有需要我可以参与维护（本人25年毕业）。

**Comment by ShevonKuan** [comment]
感谢您的提醒，目前该模板已根据23.10.10规范更新，详见 https://github.com/ShevonKuan/SCUT-thesis/releases/tag/23.10.10
1. 学位论文版权授权书更新见 https://github.com/ShevonKuan/SCUT-thesis/commit/70e77de3d023f1c47ee70549dead548a69dc24b0
2. 封面布局更新见 https://github.com/ShevonKuan/SCUT-thesis/commit/630a0aac610303142dc3fa581193b3c31e168e62
