### ISSUE TITLE
[Feature Request]希望更新新版校徽

### ISSUE THREAD

**Issue by opukhhu** [ShevonKuan/SCUT-thesis#2]
**为何需要**
模板所用校徽依然是旧版，学校规范文件中的校徽是新版，如下
![7860d90e79f01f9e832e7bee1ceeda5](https://github.com/ShevonKuan/SCUT-thesis/assets/97212210/21f4fab9-1c47-421f-978d-a8e529a6050f)
年份更改为1918年
**该需求为个人需求吗**
否

**Comment by ShevonKuan** [comment]
尊嘟假嘟，我们学校变百年老校了哎(˃ ⌑ ˂ഃ )，先咕几天再改₍˄·͈༝·͈˄*₎◞ ̑̑，因为ppt那里也得改呢(இωஇ)

**Comment by ShevonKuan** [comment]
已更新模板中的`title.png`文件为第三版校徽，由于找到的矢量图版本需要3块钱下载，就没有改演示文稿里的logo了，实在抱歉，当然咯，如果有富哥买了也可以发出来。https://www.sj51.net/74056.html
