### ISSUE TITLE
如何在overleaf中使用这个模板？

### ISSUE THREAD

**Issue by zxzxsx** [ShevonKuan/SCUT-thesis#3]
我尝试在overleaf中上传所有的模板文件并编译，但无法成功。请问这个模板是否只能用于本地呢？
![image](https://github.com/ShevonKuan/SCUT-thesis/assets/110891836/2be24964-9131-4f71-9cae-366d883c40ad)

**Comment by ShevonKuan** [comment]
这个报错可能是没有选择`xelatex`编译器导致的，也有可能是因为编译时间过长导致的，overleaf需要氪金，零氪玩家编译时间太短了，很容易报错。
