### ISSUE TITLE
本模板参考文献默认人名全大写（国标要求），但学校word模板（非论文规范，论文规范未明确指出标准）或导师要求首字母大写的解决方法。

### ISSUE THREAD

**Issue by JC-Yu** [ShevonKuan/SCUT-thesis#4]
我用VSCode编译latex文档时，发现英文参考文献列表中的人名全部是大写的，像下面这样：
![image](https://github.com/ShevonKuan/SCUT-thesis/assets/141018122/883cd68b-69f3-4bc9-91b2-1a968aa6819c)
怎么样修改成只有首字母大写的样式呢？

**Comment by ShevonKuan** [comment]
您好这是国标《信息与文献 参考文献著录规则 GB/T 7714—2015》规定的，如果您不喜欢这种可以看看 https://blog.csdn.net/X_And_Y/article/details/104867559 但是不建议做不符合规范的修改。
